# Generated by Django 6.0.6 on 2026-06-27 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled for')),
                ('key', models.CharField(choices=[('curacms', 'CuraCMS'), ('curalabs', 'CuraLabs'), ('curasuite', 'CuraSuite')], db_index=True, help_text='Unique identifier used internally and in URLs.', max_length=20, unique=True, verbose_name='Product key')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('slug', models.SlugField(help_text='Used in the URL: /products/<slug>/', max_length=120, unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(blank=True, help_text='One-line value proposition shown on cards.', max_length=200, verbose_name='Tagline')),
                ('short_description', models.TextField(help_text='Used in product cards, search results, and metadata fallback.', max_length=500, verbose_name='Short description')),
                ('long_description', models.TextField(blank=True, help_text='Full product description rendered on the product landing page.', verbose_name='Long description')),
                ('icon', models.ImageField(blank=True, help_text='Product icon — square, min 256×256px.', null=True, upload_to='products/icons/', verbose_name='Icon')),
                ('hero_image', models.ImageField(blank=True, help_text='Used in the product landing page hero section.', null=True, upload_to='products/heroes/', verbose_name='Hero image')),
                ('color', models.CharField(default='#2563EB', help_text='Hex color used for product accents. e.g. #2563EB', max_length=7, verbose_name='Brand color')),
                ('target_audience', models.TextField(blank=True, help_text='Comma-separated list: Doctors, Clinics, Pathology Labs', verbose_name='Target audience')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_published', to=settings.AUTH_USER_MODEL, verbose_name='Published by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product FAQ',
                'verbose_name_plural': 'Product FAQs',
                'db_table': 'product_faqs',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('icon_name', models.CharField(blank=True, help_text="Lucide icon name e.g. 'calendar', 'bar-chart', 'users'", max_length=50, verbose_name='Icon name')),
                ('is_highlighted', models.BooleanField(default=False, help_text='Highlighted features are shown prominently.', verbose_name='Highlighted')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
                'db_table': 'product_features',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Integration name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='products/integrations/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Integration',
                'verbose_name_plural': 'Product Integrations',
                'db_table': 'product_integrations',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=50, verbose_name='Tier name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank for 'Contact Sales' pricing.", max_digits=10, null=True, verbose_name='Price (₹)')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time'), ('custom', 'Custom / Contact Sales')], default='monthly', max_length=20, verbose_name='Billing cycle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('features_included', models.TextField(blank=True, help_text='One feature per line.', verbose_name='Features included')),
                ('is_featured', models.BooleanField(default=False, help_text='The featured tier is highlighted on the pricing page.', verbose_name='Featured tier')),
                ('cta_text', models.CharField(default='Get Started', max_length=50, verbose_name='CTA button text')),
                ('cta_url', models.CharField(blank=True, max_length=200, verbose_name='CTA URL')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Pricing',
                'verbose_name_plural': 'Product Pricing',
                'db_table': 'product_pricing',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('image', models.ImageField(upload_to='products/screenshots/', verbose_name='Screenshot')),
                ('alt_text', models.CharField(help_text='Describe the screenshot for accessibility and SEO.', max_length=200, verbose_name='Alt text')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Sort order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Screenshot',
                'verbose_name_plural': 'Product Screenshots',
                'db_table': 'product_screenshots',
                'ordering': ['sort_order'],
            },
        ),
    ]
