# Generated by Django 5.1.4 on 2026-07-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. If set and higher than Price, shown struck-through with a savings badge.', max_digits=10, null=True, verbose_name='Original price (₹)'),
        ),
    ]
