# Generated by Django 5.1.4 on 2026-07-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productpricing_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demo_url',
            field=models.URLField(blank=True, help_text="Public demo site for this product, e.g. https://cms.curasuite.app. Shown as a 'Visit Demo Website' CTA on landing pages when set.", verbose_name='Live demo URL'),
        ),
    ]
