# Generated by Django 6.0.6 on 2026-07-05 05:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled for')),
                ('slug', models.SlugField(help_text="Used as /lp/<slug>/ — e.g. 'dentist', 'pathology-digital-platform'.", max_length=100, unique=True, verbose_name='URL slug')),
                ('headline', models.CharField(max_length=200, verbose_name='Headline')),
                ('subheadline', models.CharField(blank=True, max_length=300, verbose_name='Subheadline')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='landing_pages/', verbose_name='Hero image')),
                ('target_audience_label', models.CharField(blank=True, help_text="Shown as a pill badge, e.g. 'For Dentists', 'For Pathology Labs'.", max_length=100, verbose_name='Audience label')),
                ('social_proof_note', models.CharField(blank=True, help_text="e.g. 'Trusted by 120+ dental clinics across India'.", max_length=200, verbose_name='Social proof note')),
                ('whatsapp_message_template', models.TextField(blank=True, help_text='Pre-filled message when a visitor clicks the WhatsApp CTA.', verbose_name='WhatsApp message template')),
                ('default_utm_campaign', models.CharField(blank=True, help_text="Used if the incoming ad URL doesn't carry its own utm_campaign.", max_length=100, verbose_name='Default UTM campaign')),
                ('noindex', models.BooleanField(default=True, help_text='Landing pages are usually excluded from search results and the sitemap.', verbose_name='No-index this page')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('product', models.ForeignKey(help_text='Which product this page advertises. Controls color, icon, and template family.', on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='products.product', verbose_name='Product')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_published', to=settings.AUTH_USER_MODEL, verbose_name='Published by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'db_table': 'landing_pages',
                'ordering': ['product__sort_order', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='LandingBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='✓', max_length=10, verbose_name='Icon (emoji)')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='landing_pages.landingpage')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
                'db_table': 'landing_benefits',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LandingPainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Pain point')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_points', to='landing_pages.landingpage')),
            ],
            options={
                'verbose_name': 'Pain Point',
                'verbose_name_plural': 'Pain Points',
                'db_table': 'landing_pain_points',
                'ordering': ['sort_order'],
            },
        ),
    ]
