# Generated by Django 6.0.6 on 2026-07-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='specialty',
            field=models.CharField(blank=True, help_text="Pre-fills the specialty field on the form so visitors aren't asked again — e.g. 'dentist' for the dentist landing page. Matches Lead.Specialty choices.", max_length=30, verbose_name='Specialty (auto-fill)'),
        ),
    ]
