# Generated by Django 5.1.4 on 2026-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0002_landingpage_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpainpoint',
            name='solution_text',
            field=models.CharField(blank=True, help_text='How the product solves this pain point. Shown paired with it on the landing page.', max_length=250, verbose_name='Solution'),
        ),
    ]
