# Generated by Django 5.1.4 on 2026-07-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_pages', '0003_landingpainpoint_solution_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpainpoint',
            name='consequence_text',
            field=models.CharField(blank=True, help_text="One-line real-world impact, shown under the pain point — e.g. 'Your expertise is hidden while competitors capture the local market.'", max_length=250, verbose_name='Consequence'),
        ),
    ]
