# Generated by Django 6.0.6 on 2026-06-27 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('provider', models.CharField(choices=[('google_analytics', 'Google Analytics 4'), ('google_tag_manager', 'Google Tag Manager'), ('google_ads', 'Google Ads'), ('meta_pixel', 'Meta Pixel'), ('microsoft_clarity', 'Microsoft Clarity'), ('whatsapp', 'WhatsApp Business'), ('smtp', 'SMTP Email'), ('recaptcha', 'reCAPTCHA / Turnstile'), ('gemini', 'Google Gemini AI'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('brevo', 'Brevo (Email)'), ('mailchimp', 'Mailchimp')], db_index=True, max_length=30, unique=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='Enabled')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Non-secret configuration JSON. Store secrets in environment variables.', verbose_name='Configuration')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('error', 'Error'), ('', 'Not tested')], max_length=10)),
                ('last_test_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'db_table': 'integrations',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=20, verbose_name='GA4 Measurement ID')),
                ('gtm_container_id', models.CharField(blank=True, help_text='e.g. GTM-XXXXXXX', max_length=20, verbose_name='GTM Container ID')),
                ('meta_pixel_id', models.CharField(blank=True, max_length=30, verbose_name='Meta Pixel ID')),
                ('clarity_project_id', models.CharField(blank=True, max_length=20, verbose_name='Microsoft Clarity ID')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='Enable WhatsApp widget')),
                ('whatsapp_phone', models.CharField(blank=True, help_text='International format without +: e.g. 919876543210', max_length=20, verbose_name='WhatsApp phone number')),
                ('whatsapp_message', models.CharField(blank=True, default="Hi! I'd like to know more about CuraSuite.", max_length=200, verbose_name='Pre-filled message')),
                ('whatsapp_tooltip', models.CharField(blank=True, default='Chat with us', max_length=100, verbose_name='Tooltip text')),
                ('chatbot_enabled', models.BooleanField(default=False, verbose_name='Enable AI chatbot')),
                ('chatbot_name', models.CharField(default='CuraSuite Assistant', max_length=50, verbose_name='Chatbot name')),
                ('chatbot_greeting', models.CharField(default="Hi! I'm the CuraSuite Assistant. How can I help you today?", max_length=300, verbose_name='Greeting message')),
                ('chatbot_system_prompt', models.TextField(blank=True, default="You are the CuraSuite Assistant, a helpful AI for CuraSuite — India's healthcare technology platform. Help visitors understand our products (CuraCMS, CuraLabs, CuraSuite), answer questions about features and pricing, and guide them to book a demo. Be friendly, professional, and concise. For medical advice, always direct users to qualified healthcare professionals.", help_text='Instructions for the AI. Keep focused on CuraSuite products and healthcare technology.', verbose_name='System prompt')),
                ('captcha_enabled', models.BooleanField(default=False, verbose_name='Enable CAPTCHA on forms')),
                ('captcha_provider', models.CharField(choices=[('recaptcha_v3', 'reCAPTCHA v3'), ('turnstile', 'Cloudflare Turnstile')], default='turnstile', max_length=15, verbose_name='CAPTCHA provider')),
                ('captcha_site_key', models.CharField(blank=True, max_length=200, verbose_name='Site key (public)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
