# Generated by Django 6.0.6 on 2026-06-28 01:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementBar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Announcement text')),
                ('link_text', models.CharField(blank=True, max_length=50, verbose_name='Link text')),
                ('link_url', models.CharField(blank=True, max_length=200, verbose_name='Link URL')),
                ('style', models.CharField(choices=[('info', 'Info (Blue)'), ('success', 'Success (Green)'), ('warning', 'Warning (Amber)'), ('promo', 'Promo (Black)')], default='info', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Active')),
                ('is_dismissible', models.BooleanField(default=True, verbose_name='Dismissible by user')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Show from')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Hide after')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Announcement Bar',
                'verbose_name_plural': 'Announcement Bars',
                'db_table': 'announcement_bars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('category', models.CharField(choices=[('general', 'General'), ('pricing', 'Pricing'), ('technical', 'Technical'), ('support', 'Support'), ('security', 'Security')], default='general', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global FAQ',
                'verbose_name_plural': 'Global FAQs',
                'db_table': 'global_faqs',
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RobotsTxt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='User-agent: *\nAllow: /\nDisallow: /manage/\nDisallow: /admin/\n\nSitemap: https://curasuite.com/sitemap.xml\n', verbose_name='robots.txt content')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Robots.txt',
                'db_table': 'robots_txt',
            },
        ),
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=200, verbose_name='SMTP Host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Port')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Username / Email')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('from_email', models.EmailField(default='hello@curasuite.com', max_length=254, verbose_name='From email')),
                ('from_name', models.CharField(default='CuraSuite', max_length=100, verbose_name='From name')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Connection verified')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Settings',
                'db_table': 'smtp_settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_x', models.URLField(blank=True, verbose_name='X / Twitter')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('whatsapp_link', models.URLField(blank=True, verbose_name='WhatsApp Business Link')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Links',
                'db_table': 'social_links',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer name')),
                ('designation', models.CharField(blank=True, max_length=200, verbose_name='Designation / Role')),
                ('clinic_name', models.CharField(blank=True, max_length=200, verbose_name='Clinic / Organisation')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='City / Location')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('feedback', models.TextField(verbose_name='Testimonial text')),
                ('product', models.CharField(blank=True, help_text='CuraCMS, CuraLabs, CuraSuite, or blank for general', max_length=50, verbose_name='Product')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured on homepage')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
