# Generated by Django 5.1.4 on 2026-07-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='specialty',
            field=models.CharField(blank=True, help_text="Matches Lead.Specialty / LandingPage.specialty values, e.g. 'dentist'. Leave blank for a general testimonial not tied to one vertical. Used to make sure a landing page only ever shows same-niche testimonials (never a physiotherapist quote on a dentist page).", max_length=30, verbose_name='Specialty'),
        ),
    ]
