# Generated by Django 6.0.6 on 2026-06-27 08:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(db_index=True, help_text='The URL path being redirected FROM. Must start with /', max_length=500, unique=True, verbose_name='Old path')),
                ('new_path', models.CharField(help_text='The URL path redirecting TO. Can be absolute or relative.', max_length=500, verbose_name='New path')),
                ('redirect_type', models.CharField(choices=[('301', '301 — Permanent'), ('302', '302 — Temporary')], default='301', max_length=3, verbose_name='Redirect type')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text='Internal note about why this redirect exists.', max_length=255, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'db_table': 'seo_redirects',
                'ordering': ['old_path'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('object_id', models.UUIDField(verbose_name='Object ID')),
                ('seo_title', models.CharField(blank=True, help_text='Recommended 50–60 characters. Defaults to content title if blank.', max_length=70, verbose_name='SEO title')),
                ('meta_description', models.CharField(blank=True, help_text='Recommended 140–160 characters.', max_length=165, verbose_name='Meta description')),
                ('canonical_url', models.URLField(blank=True, help_text="Leave blank to use the page's default URL.", verbose_name='Canonical URL')),
                ('robots', models.CharField(choices=[('index, follow', 'Index, Follow (default)'), ('noindex, follow', 'No Index, Follow'), ('index, nofollow', 'Index, No Follow'), ('noindex, nofollow', 'No Index, No Follow')], default='index, follow', max_length=30, verbose_name='Robots directive')),
                ('og_title', models.CharField(blank=True, max_length=100, verbose_name='OG title')),
                ('og_description', models.TextField(blank=True, max_length=300, verbose_name='OG description')),
                ('og_image', models.ImageField(blank=True, help_text='Recommended 1200×630px.', null=True, upload_to='seo/og/', verbose_name='OG image')),
                ('twitter_title', models.CharField(blank=True, max_length=100, verbose_name='Twitter title')),
                ('twitter_description', models.CharField(blank=True, max_length=200, verbose_name='Twitter description')),
                ('schema_type', models.CharField(blank=True, choices=[('', 'None'), ('Organization', 'Organization'), ('WebSite', 'Website'), ('SoftwareApplication', 'Software Application'), ('Product', 'Product'), ('Article', 'Article'), ('BlogPosting', 'Blog Posting'), ('FAQPage', 'FAQ Page'), ('HowTo', 'How To'), ('LocalBusiness', 'Local Business'), ('BreadcrumbList', 'Breadcrumb List')], default='', max_length=30, verbose_name='Schema type')),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword this page targets.', max_length=100, verbose_name='Focus keyword')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'db_table': 'seo_metadata',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_metadat_content_600398_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
