# Generated by Django 6.0.6 on 2026-06-27 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organization')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('business_type', models.CharField(blank=True, choices=[('single_doctor', 'Single Doctor'), ('multi_specialty', 'Multi-Specialty Clinic'), ('dental', 'Dental Clinic'), ('physiotherapy', 'Physiotherapy Clinic'), ('pathology_lab', 'Pathology Lab'), ('diagnostic', 'Diagnostic Center'), ('hospital', 'Hospital'), ('other', 'Other')], max_length=30, verbose_name='Business type')),
                ('product_interest', models.CharField(blank=True, help_text='Which CuraSuite product are they interested in?', max_length=100, verbose_name='Product interest')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('demo_scheduled', 'Demo Scheduled'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('unqualified', 'Unqualified')], db_index=True, default='new', max_length=20, verbose_name='Status')),
                ('score', models.PositiveIntegerField(default=0, help_text='Higher score = higher priority. Set manually or via automation.', verbose_name='Lead score')),
                ('source', models.CharField(choices=[('contact_form', 'Contact Form'), ('demo_form', 'Demo Request Form'), ('newsletter', 'Newsletter Signup'), ('google_ads', 'Google Ads'), ('meta_ads', 'Meta Ads'), ('organic', 'Organic Search'), ('referral', 'Referral'), ('chatbot', 'AI Chatbot'), ('direct', 'Direct'), ('other', 'Other')], default='other', max_length=20, verbose_name='Source')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM campaign')),
                ('utm_content', models.CharField(blank=True, max_length=100, verbose_name='UTM content')),
                ('referrer_url', models.URLField(blank=True, verbose_name='Referrer URL')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'crm_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Preferred date')),
                ('preferred_time', models.CharField(blank=True, max_length=50, verbose_name='Preferred time')),
                ('product_interest', models.CharField(blank=True, max_length=100, verbose_name='Product of interest')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=15)),
                ('notes', models.TextField(blank=True, verbose_name='Internal notes')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_demos', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_requests', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'db_table': 'crm_demo_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Lead Created'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('email_sent', 'Email Sent'), ('call_logged', 'Call Logged'), ('demo_booked', 'Demo Booked'), ('assigned', 'Lead Assigned')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'db_table': 'crm_lead_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'db_table': 'crm_lead_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='crm_leads_status_26893f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'created_at'], name='crm_leads_source_147955_idx'),
        ),
    ]
