# Generated by Django 6.0.6 on 2026-07-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='specialty',
            field=models.CharField(blank=True, choices=[('general_physician', 'General Physician'), ('dentist', 'Dentist'), ('physiotherapist', 'Physiotherapist'), ('ophthalmologist', 'Ophthalmologist'), ('pathology_lab', 'Pathology Lab'), ('other', 'Other')], help_text='Doctor / practice specialty — captured via icon-based selector.', max_length=30, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email'),
        ),
    ]
