# Generated by Django 6.0.6 on 2026-06-27 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Folder name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='media.mediafolder', verbose_name='Parent folder')),
            ],
            options={
                'verbose_name': 'Media Folder',
                'verbose_name_plural': 'Media Folders',
                'db_table': 'media_folders',
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('file', models.FileField(upload_to='media-library/%Y/%m/', verbose_name='File')),
                ('original_name', models.CharField(max_length=255, verbose_name='Original filename')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME type')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document / PDF'), ('video', 'Video'), ('svg', 'SVG'), ('other', 'Other')], db_index=True, default='other', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='File size (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (px)')),
                ('alt_text', models.CharField(blank=True, help_text='Required for images — describes the image for accessibility and SEO.', max_length=200, verbose_name='Alt text')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('caption', models.TextField(blank=True, max_length=500, verbose_name='Caption')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated.', max_length=500, verbose_name='Tags')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='media.mediafolder', verbose_name='Folder')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_type', 'created_at'], name='media_files_file_ty_785495_idx'), models.Index(fields=['folder', 'file_type'], name='media_files_folder__c14905_idx')],
            },
        ),
    ]
