# Generated by Django 6.0.6 on 2026-06-27 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In Review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Published at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled for')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('product', 'Product Landing'), ('solution', 'Solution'), ('feature', 'Feature'), ('pricing', 'Pricing'), ('contact', 'Contact'), ('blog_index', 'Blog Index'), ('legal', 'Legal'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('template', models.CharField(choices=[('default', 'Default'), ('full_width', 'Full Width'), ('landing', 'Landing Page'), ('minimal', 'Minimal (no header/footer)')], default='default', max_length=20)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary used in listings and SEO fallback.', max_length=500, verbose_name='Excerpt')),
                ('content', models.TextField(blank=True, help_text='Main page content (HTML or Markdown).', verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Featured image')),
                ('show_in_sitemap', models.BooleanField(default=True, verbose_name='Show in sitemap')),
                ('show_in_nav', models.BooleanField(default=False, verbose_name='Show in navigation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page', verbose_name='Parent page')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_published', to=settings.AUTH_USER_MODEL, verbose_name='Published by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('revision_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page Revision',
                'verbose_name_plural': 'Page Revisions',
                'db_table': 'page_revisions',
                'ordering': ['-revision_number'],
            },
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'slug'], name='pages_status_740be2_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['page_type', 'status'], name='pages_page_ty_1f355e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pagerevision',
            unique_together={('page', 'revision_number')},
        ),
    ]
