# Generated by Django 5.1.4 on 2026-07-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', 'Default'), ('full_width', 'Full Width'), ('landing', 'Landing Page'), ('minimal', 'Minimal (no header/footer)'), ('about', 'About Page'), ('solutions', 'Solutions Page'), ('pricing', 'Pricing Page')], default='default', max_length=20),
        ),
    ]
